# Generated by Django 2.0.5 on 2019-06-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
